version: '3.8'

services:
  # 🗄️ O Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql_comentaae
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: )Sc4WS@%hX?y!{]u
      MYSQL_DATABASE: db_comentaae
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 🚀 O seu App Node.js (Comentaaê)
  app:
    build: .
    container_name: app_comentaae
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

# 💾 Volume para os dados
volumes:
  db_data:


