services:
  db:
    image: mysql:8.0
    container_name: mysql_comentaae
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ")Sc4WS@%hX?y!{]u"
      MYSQL_DATABASE: db_comentaae
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: app_comentaae
    restart: always
    environment:
      - PORT=3000
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx_comentaae
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  db_data:
