events { worker_connections 1024; }

http {
    upstream ssr_cluster {
    server app:3000; # Antes estava app_ssr:3001
}

    server {
        listen 80;
        server_name comentaae.com www.comentaae.com;

        location / {
            proxy_pass http://ssr_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}